# To run:
# docker-compose up --build
#
# To run in detached mode:
# docker-compose up --build -d
#
# To stop:
# docker-compose down
#
# To rebuild and run:
# docker-compose down && docker-compose up --build

services:
    extensionjs:
        build:
            context: .
            dockerfile: Dockerfile.extensionjs
        container_name: extensionjs
        ports:
            - "10000:10000" # Xpra HTML client
            - "3001:3001" # Server port
            - "8000:8000" # Additional server port
        volumes:
            - ./extension:/tmp/extension
        restart: unless-stopped
        environment:
            - DISPLAY=:100
        # Optional: Add resource limits
        # deploy:
        #   resources:
        #     limits:
        #       memory: 2G
        #     reservations:
        #       memory: 1G
